### ISSUE TITLE
JPG with capitalized extension fails to upload

### ISSUE THREAD

**Issue by kitt** [howbadprettybad/superyesmore#1]
I tried uploading a JPG image with the name IMG_7872.JPG - it failed to upload with a "Please use a valid mime type" message.  I renamed the file to lowercase .jpg, and it uploaded successfully.  Repeated with a different image.

Might be with all capitalized extensions, I didn't check.

**Comment by alexduloz** [comment]
Capitalized extensions.

Many thanks for your feedback. I will close this issue as soon as the new version of the app goes live.

**Comment by kitt** [comment]
👍🏼
