### ISSUE TITLE
RSS feed

### ISSUE THREAD

**Issue by susanjrobertson** [howbadprettybad/superyesmore#2]
I tried a couple of different urls to add The Human Machine to my feed reader and nothing worked. It'd be great to be able to see it in my feed every day.

**Comment by alexduloz** [comment]
I've added two feeds. 

1. One which mimics the "Stream" page:
https://superyesmore.com/stream
https://superyesmore.com/feed/rss2

2. One which shows only the articles for a given publication
https://superyesmore.com/publication/the-human-in-the-machine-a4064599cde2cb3397239e8d72219f48/feed/rss2

I won't close the issue right now. If you could provide some feedback that would be awesome.

**Comment by susanjrobertson** [comment]
Wow, that was so quick Alex, thank you so much!

They all work in feedly (which is what I use), the show the summary and that's enough for me to know it's there and click to read more :)

**Comment by alexduloz** [comment]
Added a feed for authors. Example: https://superyesmore.com/who/is/alexduloz

Don't hesitate to repoen the issue if there's... an issue. :)
