### ISSUE TITLE
Typo "Your email subscribtions" in "..." tooltip

### ISSUE THREAD

**Issue by awelfle** [howbadprettybad/superyesmore#3]
"Subscriptions" is misspelled in the ellipses menu in the action line of both the article permalink and the publications permalink.

Current string:
Your email subscribtions

Updated string: 
Your email subscriptions

![screen_shot_2017-01-06_at_8_52_44_am](https://cloud.githubusercontent.com/assets/1836249/21725560/c66f53f4-d3ed-11e6-9d83-f5df1cf3bcb8.png)

**Comment by alexduloz** [comment]
Thank you so much. The typo appeared in several places.
